services:
  bot:
    build: ./bot/
    secrets:
      - bot_token

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - db_data:/pb_data
      - ./api:/pb_public
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
    driver: local
  cache:
    driver: local

secrets:
  bot_token:
    file: ./token.key